### PR TITLE
Don't try to process drives if `--help` is called

### LINKED ISSUE #164: Not possible to see `whipper cd` --help messages without optical drive
Trying to get `--help` for `whipper cd` or any of its subcommands (well, `rip` at least) fails when there's no CD-DA drive:
```python-traceback
~> whipper cd --help
CRITICAL:whipper.command.basecommand:No CD-DA drives found!
Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.5.1', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/site-packages/whipper/command/main.py", line 31, in main
    cmd = Whipper(sys.argv[1:], os.path.basename(sys.argv[0]), None)
  File "/usr/lib/python2.7/site-packages/whipper/command/basecommand.py", line 102, in __init__
    self.options
  File "/usr/lib/python2.7/site-packages/whipper/command/basecommand.py", line 72, in __init__
    raise IOError(msg)
IOError: No CD-DA drives found!
```
Actual CD commands should definitely fail without a drive, but it should be possible to still get help messages.

### PR DESCRIPTION
**Pull request by pieqq**
Fixes #164

### CODE REVIEW

**Comment by pierrrrrrre** [comment]
Now, on a device without optical drive:

```bash
% whipper cd --help                                                                         [~/dev/whipper]
usage: whipper cd [-h]

Display and rip CD-DA and metadata.

optional arguments:
  -h, --help  show this help message and exit

commands:
  info     retrieve information about the currently inserted CD
  rip      rip CD
```

```bash
% whipper cd rip --help                                                                     [~/dev/whipper]
usage: whipper cd rip [-h] [-T TOC_PICKLE] [-R RELEASE_ID] [-p] [-c COUNTRY]
                      [-L LOGGER] [-o OFFSET] [-x] [-O OUTPUT_DIRECTORY]
                      [-W WORKING_DIRECTORY] [--track-template TRACK_TEMPLATE]
                      [--disc-template DISC_TEMPLATE] [-U] [--cdr]

Rips a CD. Tracks are named according to the track template, filling in the
variables and adding the file extension. Variables exclusive to the track
template are: - %t: track number - %a: track artist - %n: track title - %s:
track sort name Disc files (.cue, .log, .m3u) are named according to the disc
template, filling in the variables and adding the file extension. Variables
for both disc and track template are: - %A: album artist - %S: album sort name
- %d: disc title - %y: release year - %r: release type, lowercase - %R:
Release type, normal case - %x: audio extension, lowercase - %X: audio
extension, uppercase Paths to track files referenced in .cue and .m3u files
will be made relative to the directory of the disc files. All files will be
created relative to the given output directory. Log files will log the path to
tracks relative to this directory.

optional arguments:
  -h, --help            show this help message and exit
  -T TOC_PICKLE, --toc-pickle TOC_PICKLE
                        pickle to use for reading and writing the TOC
                        (default: None)
  -R RELEASE_ID, --release-id RELEASE_ID
                        MusicBrainz release id to match to (if there are
                        multiple) (default: None)
  -p, --prompt          Prompt if there are multiple matching releases
                        (default: False)
  -c COUNTRY, --country COUNTRY
                        Filter releases by country (default: None)
  -L LOGGER, --logger LOGGER
                        whipper') (default: whipper)
  -o OFFSET, --offset OFFSET
                        sample read offset (default: None)
  -x, --force-overread  Force overreading into the lead-out portion of the
                        disc. Works only if the patched cdparanoia package is
                        installed and the drive supports this feature.
                        (default: False)
  -O OUTPUT_DIRECTORY, --output-directory OUTPUT_DIRECTORY
                        output directory; will be included in file paths in
                        log (default: .)
  -W WORKING_DIRECTORY, --working-directory WORKING_DIRECTORY
                        working directory; whipper will change to this
                        directory and files will be created relative to it
                        when not absolute (default: None)
  --track-template TRACK_TEMPLATE
                        template for track file naming (default: %r/%A -
                        %d/%t. %a - %n.%x)
  --disc-template DISC_TEMPLATE
                        template for disc file naming (default: %r/%A - %d/%A
                        - %d)
  -U, --unknown         whether to continue ripping if the CD is unknown
                        (default: False)
  --cdr                 whether to continue ripping if the disc is a CD-R
                        (default: False)
```

**Comment by pierrrrrrre** [comment]
@Freso thanks for the feedback!

Yes, it could be a good idea to write some unit tests for this. But before that I'd like to know how to reliably run the existing unit tests... I've tried a few things but it all fails all the time... Do I need to setup a virtualenv? What packages do I need to run the tests? There is [no doc for this part.](https://github.com/JoeLametta/whipper#developing)

Thanks!

**Comment by RecursiveForest** [comment]
Setting up a virtualenv for a project is always recommended for developing python. The test dependencies and commands can be found in `.travis.yml`.

**Comment by pieqq** [comment]
@RecursiveForest thanks for the feedback! I managed to run the tests but I still had to install a lot of dependencies using `apt install`, which means they couldn't be installed in a virtualenv. If you have a better way of doing things, please let me know.

@Freso I had a look at the kind of tests I could write, but I'm a bit lost. It looks like this MR would require more of a functional test rather than unit test (e.g. "if I run `whipper --help`, I should have the following output whether I have a drive or not). What kind of unit test could I write to make sure we don't have regressions in the future? Thanks!

**Comment by Freso** [comment]
I didn't say it had to be a unit test. :) However, it would be good with a unit test for `Rip.add_arguments()` - run without setting `self.opts.device` and run with setting `self.opts.device` and make sure it gets expected output both times. You can also test the `BaseCommand()` class.

**Comment by RecursiveForest** [comment]
And for the record, this looks fine to me but I echo @Freso 's request for a test of the functionality.

**Comment by pieqq** [comment]
@RecursiveForest Thanks for the feedback!

Sorry I didn't spend enough time on this to generate proper tests, but I spent enough time to find out my changes brought a regression in a lot of commands afterwards, so:

- I need to think of a better way to handle this
- Tests are definitely needed :)

I'll close that pull request. If I have something better to propose, I'll do so later (unfortunately, life's keeping me busy on other stuff :)).

**Pull request closed without merging**
