### PR TITLE
Update README.md with dependencies install for Ubuntu 16.04

### PR DESCRIPTION
**Pull request by inverse**
Added installing dependencies for Ubuntu

### CODE REVIEW

**Comment by inverse** [comment]
Should be ready to go. The first changes were done when installing. Second round of changes were done when running on another machine.

**Comment by inverse** [comment]
Unfortunately Ubuntu `16.10` has `python-gst-1.0` which this isn't compatible with from my understanding.

**Comment by JoeLametta** [comment]
> If you feel this is not relevant here should we put them in the Wiki?

I Don't know and, unfortunately, this period I haven't got a lot of time to spend on whipper. In the meantime I think you can surely add it to the wiki (which everybody should be able to edit).

Thanks

**Comment by inverse** [comment]
Updated wiki

**Pull request closed without merging**
