### PR TITLE
Readme rewrite

### PR DESCRIPTION
**Pull request by RecursiveForest**
Overall I like the new README, but I thought a few sections could be less conversational and more terse. These are those changes.

### CODE REVIEW

**Comment by JoeLametta** [comment]
Looks fine. The "Getting started" section is now probably a bit too slim (especially for newcomers).
Something still missing is an explicit section about whipper's plugin support (loggers).

**Comment by RecursiveForest** [comment]
I agree regarding the loggers. I completely disagree regarding 'Getting started'; all the same meaningful information is there, but in a more readeable format.

**Comment by JoeLametta** [comment]
> I completely disagree regarding 'Getting started'; all the same meaningful information is there, but in a more readeable format.

OK, hopefully newbies will find it easier to follow.

**Comment by RecursiveForest** [comment]
Yeah, I am fine writing the logging section, as I have done.

**Comment by JoeLametta** [comment]
> Yeah, I am fine writing the logging section, as I have done.

If it's finished I'm going to merge it.

**Pull request merged**
