### PR TITLE
Run whipper without installation

### PR DESCRIPTION
**Pull request by vmx**
This commit makes it possible to run whipper directly with
`python -m whipper` from wither within the source directory
or with `PYTHONPATH` set to the source directory.

I'm not sure if that's generally useful or people other than my like running programs like that.

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
An alternative for you could be to set "$PATH" to "$PATH:`pwd`". I think the README mentions a way to run whipper uninstalled.

**Comment by vmx** [comment]
@MerlijnWajer The path is only added when running via `python -m whipper` not when installed in other ways (at least that was my plan).

**Comment by MerlijnWajer** [comment]
Oops, you're right. I think this is OK. @Freso - got an opinion on this?

**Comment by MerlijnWajer** [comment]
@Freso seems to ACK this.

**Comment by MerlijnWajer** [comment]
Thank you.

**Pull request merged**
