### PR TITLE
test HTOA peak value against 0.0 instead of 1e-10

### PR DESCRIPTION
**Pull request by RecursiveForest**

### CODE REVIEW

**Comment by RecursiveForest** [comment]
To make myself feel better about 'SILENT', I think this only became possible once we switched to `sox`. Not totally sure about that, though.

**Comment by MerlijnWajer** [comment]
Are you sure this is related to sox? I thought that there was usually always a bit of noise/jitter, so 0 would not work?

**Comment by JoeLametta** [comment]
Yeah the correct way to handle this one depends on how we define `SILENT`:

1. Digitally silent (all the HTOA's samples have value == −32768)
2. A threshold (what would be the rationale of this choice and how do we choose which value to use as reference for `SILENT`?)

**Comment by RecursiveForest** [comment]
Alright.

**Pull request closed without merging**
