### PR TITLE
Revert "Convert docstrings to reStructuredText"

### PR DESCRIPTION
**Pull request by RecursiveForest**
This reverts commit 3b1bd242d09bfc5e8d3070138e76999f2b510e22.

I'm not sure what the intended goal of this change was. Almost all of our docstrings are internal developer documentation and should stay as lean as possible to not waste screen space. I don't see any reason to bring back the old morituri-style bloat of useless and unnecessary parameter lists, especially when their "type" field is often incorrectly the same string as the parameter value.

Joe, please follow convention and create pull requests for your own changes, *especially* large style-changing ones like this, **and give us a chance to review them**, instead of essentially merging them directly to master with a merge bubble.

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
I don't mind making rst comments multiline. I have to look up what the right way to define parameters in function comments is, but I think that's also fine. The weird "I (as a function) do this" can go, though.

I'm assuming this was done in part to please some tools that complain about missing doc?

**Comment by RecursiveForest** [comment]
I don't mind multiline docstrings, the param/type lists just provide almost no value. I feel very strongly about this.

**Comment by RecursiveForest** [comment]
I should also state that I don't mind the whitespace and formatting changes that were part of this PR-- those were all good (although I'd advise creating them as a separate PR to make tracking changes easier). I don't even mind using rST for parts of our docstrings (like spelling code snippets with backticks, etc), but I *do* mind adding boilerplate parameter lists to function docstrings.

**Comment by JoeLametta** [comment]
Fine, let's merge this then rework that commit.

**Comment by RecursiveForest** [comment]
Okay, I'll resolve the new conflicts when I get home.

**Comment by RecursiveForest** [comment]
Resolved.

**Pull request merged**
