### PR TITLE
use setuptools, remove autohell, use raw make for src/

### PR DESCRIPTION
**Pull request by RecursiveForest**
Use setup.py for whipper python modules & 'rip' command.
Remove autohell vomit.
Use a minimal 'Makefile' for the bundled program in src/.

Accordingly, I updated the README with instructions. This will also make changing the 'rip' command per https://github.com/JoeLametta/whipper/issues/21 trivial.

### CODE REVIEW

**Comment by RecursiveForest** [comment]
Uh, travis-ci will need to be updated. ;)

**Comment by RecursiveForest** [comment]
I also cleaned up a bit of the dogfooded project management stuff. I don't think I nuked all of it, but at least enough to feel good about things.

**Comment by JoeLametta** [comment]
Merged, thank you very much.
I'm going to fix/silence that broken tests right now.

**Comment by RecursiveForest** [comment]
I, for testing purposes, bumped the version number to 0.3.0 as you saw, and because of limitations I didn't implement any of the hacks I found online of synchronising the version number, so it's in both morituri/configure/configure.py and setup.py.

**Pull request merged**
