### PR TITLE
Incremental code modernization for (future) Python 3 port

### PR DESCRIPTION
**Pull request by JoeLametta**
This is a WIP.
I'm trying to introduce only incremental changes which can be merged right now because they retain backward compatibility with Python 2 (but explicitly target Python 3). The aim is to simplify the porting effort that will take place after milestone 1.0 has been reached.

### CODE REVIEW

**Comment by JoeLametta** [comment]
I'd like to merge this PR to master: time will tell if it breaks something...

:rofl:

**Comment by mtdcr** [comment]
https://github.com/JoeLametta/whipper/pull/268/commits/44ece38740c5f30a2fc87500137784e64f1f291d introduces many lines with superflous braces like print((...)), where print already was used as a function. Did you do the conversion using a script?

**Comment by JoeLametta** [comment]
> 44ece38 introduces many lines with superflous braces like print((...)), where print already was used as a function. Did you do the conversion using a script?

Yeah, some of the changes were guided by Python's `2to3` tool. Anyway I think this specific issue was already fixed in https://github.com/JoeLametta/whipper/pull/268/commits/0f67bc4a96125b27fc3004a6779ef4e49ee2e65d: am I right?

**Comment by mtdcr** [comment]
Oh, sorry, I hadn't noticed https://github.com/JoeLametta/whipper/commit/0f67bc4a96125b27fc3004a6779ef4e49ee2e65d.

**Pull request merged**
